GRANT ALL ON WIKIDBNAME.* to 'WIKIDBUSER'@'127.0.0.1' IDENTIFIED BY 'WIKIDBPASS';
GRANT ALL ON WIKIDBNAME.* to 'WIKIDBUSER'@'localhost' IDENTIFIED BY 'WIKIDBPASS';
GRANT ALL ON WIKIDBNAME.* to 'WIKIDBUSER'@'::1' IDENTIFIED BY 'WIKIDBPASS';
FLUSH PRIVILEGES;